# Generated by Django 3.2.18 on 2023-02-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='type',
            field=models.ImageField(choices=[(1, 'Form'), (2, 'Api')], default=1, upload_to=''),
        ),
    ]
