# Generated by Django 3.2.18 on 2023-03-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeypot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip address')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
    ]
